### ISSUE TITLE
Solution branch naming is backwards from lab

### ISSUE THREAD

**Issue by rogerprz** [learn-co-curriculum/M4-DQ4-Passing-Callbacks-to-Comrade-Hogs-in-React#5]
Your solution branch naming is not the same as the regular branch.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
